#!/usr/bin/env bash
set -euo pipefail

# setup-local.sh — Set up the Aionima ID service for local self-hosting.
#
# Three PostgreSQL options:
#   1. Existing PostgreSQL instance (user provides connection string)
#   2. Install via apt + create database
#   3. Podman container (preferred, uses AGI's container manager)
#
# Usage:
#   ./scripts/setup-local.sh [--db-url <url>] [--db-apt] [--db-podman]
#   ./scripts/setup-local.sh --help

ID_DIR="${AIONIMA_ID_DIR:-/opt/aionima-id}"
SERVICE_USER="${AIONIMA_USER:-$(whoami)}"
DB_NAME="aionima_id"
DB_USER="aionima_id"
DB_PASS=""
DB_URL=""
DB_MODE=""

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --db-url)    DB_MODE="url";    DB_URL="$2"; shift 2 ;;
    --db-apt)    DB_MODE="apt";    shift ;;
    --db-podman) DB_MODE="podman"; shift ;;
    --help|-h)
      echo "Usage: setup-local.sh [--db-url <url>] [--db-apt] [--db-podman]"
      echo ""
      echo "Options:"
      echo "  --db-url <url>    Use an existing PostgreSQL instance"
      echo "  --db-apt          Install PostgreSQL via apt and create a database"
      echo "  --db-podman       Run PostgreSQL in a Podman container (default)"
      echo ""
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Default to podman
DB_MODE="${DB_MODE:-podman}"

echo "=== Aionima ID Service — Local Setup ==="
echo "Directory: $ID_DIR"
echo "User:      $SERVICE_USER"
echo "DB mode:   $DB_MODE"
echo ""

# ---------------------------------------------------------------------------
# Ensure ID service directory exists
# ---------------------------------------------------------------------------
if [ ! -d "$ID_DIR" ]; then
  echo "ID service directory not found at $ID_DIR"
  echo "Clone the repo first: git clone git@github.com:Civicognita/aionima-id.git $ID_DIR"
  exit 1
fi

# ---------------------------------------------------------------------------
# Generate encryption key if not present
# ---------------------------------------------------------------------------
ENV_FILE="$ID_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "Creating .env file..."
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  cat > "$ENV_FILE" <<EOF
# Aionima ID Service — Local Configuration
# Generated by setup-local.sh

ID_SERVICE_MODE=local
PORT=3200
ENCRYPTION_KEY=$ENCRYPTION_KEY

# PostgreSQL (set by setup script below)
# DATABASE_URL=

# OAuth credentials (optional — add as needed)
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=
EOF
  echo "Generated .env with encryption key"
fi

# ---------------------------------------------------------------------------
# PostgreSQL setup
# ---------------------------------------------------------------------------
case "$DB_MODE" in
  url)
    if [ -z "$DB_URL" ]; then
      echo "Error: --db-url requires a connection string"
      exit 1
    fi
    # Update .env with the provided URL
    if grep -q "^DATABASE_URL=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DB_URL|" "$ENV_FILE"
    else
      echo "DATABASE_URL=$DB_URL" >> "$ENV_FILE"
    fi
    echo "Using existing PostgreSQL: $DB_URL"
    ;;

  apt)
    echo "Installing PostgreSQL via apt..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq postgresql postgresql-client

    # Generate password
    DB_PASS=$(openssl rand -hex 16)

    # Create user and database
    sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';" 2>/dev/null || true
    sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || true
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;" 2>/dev/null || true

    DB_URL="postgres://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME"

    if grep -q "^DATABASE_URL=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DB_URL|" "$ENV_FILE"
    else
      echo "DATABASE_URL=$DB_URL" >> "$ENV_FILE"
    fi
    echo "PostgreSQL installed and configured"
    echo "Database: $DB_NAME, User: $DB_USER"
    ;;

  podman)
    echo "Setting up PostgreSQL via Podman container..."

    # Check podman is available
    if ! command -v podman &>/dev/null; then
      echo "Error: podman not found. Install podman first or use --db-apt."
      exit 1
    fi

    DB_PASS=$(openssl rand -hex 16)
    CONTAINER_NAME="aionima-id-postgres"

    # Stop and remove existing container if present
    podman rm -f "$CONTAINER_NAME" 2>/dev/null || true

    # Create persistent volume
    podman volume create aionima-id-pgdata 2>/dev/null || true

    # Run PostgreSQL container
    podman run -d \
      --name "$CONTAINER_NAME" \
      --restart unless-stopped \
      -e POSTGRES_DB="$DB_NAME" \
      -e POSTGRES_USER="$DB_USER" \
      -e POSTGRES_PASSWORD="$DB_PASS" \
      -v aionima-id-pgdata:/var/lib/postgresql/data \
      -p 5433:5432 \
      docker.io/postgres:16-alpine

    DB_URL="postgres://$DB_USER:$DB_PASS@localhost:5433/$DB_NAME"

    if grep -q "^DATABASE_URL=" "$ENV_FILE" 2>/dev/null; then
      sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DB_URL|" "$ENV_FILE"
    else
      echo "DATABASE_URL=$DB_URL" >> "$ENV_FILE"
    fi

    echo "PostgreSQL container started: $CONTAINER_NAME (port 5433)"
    echo "Database: $DB_NAME, User: $DB_USER"
    ;;
esac

# ---------------------------------------------------------------------------
# Install dependencies and build
# ---------------------------------------------------------------------------
echo ""
echo "Installing dependencies..."
cd "$ID_DIR"
npm install --omit=dev 2>&1 | tail -1

echo "Building..."
npm run build 2>&1 | tail -1

# ---------------------------------------------------------------------------
# Run migrations
# ---------------------------------------------------------------------------
echo "Running database migrations..."

# Source .env for migration
set -a
source "$ENV_FILE"
set +a

npx drizzle-kit migrate 2>&1 | tail -3

# ---------------------------------------------------------------------------
# Install systemd service
# ---------------------------------------------------------------------------
echo ""
echo "Installing systemd service..."
RENDERED=$(sed "s/%AIONIMA_USER%/$SERVICE_USER/g" "$ID_DIR/aionima-id.service")
echo "$RENDERED" | sudo tee /etc/systemd/system/aionima-id.service >/dev/null
sudo systemctl daemon-reload
sudo systemctl enable aionima-id

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Start the service:  sudo systemctl start aionima-id"
echo "View logs:          journalctl -u aionima-id -f"
echo "Service URL:        http://localhost:${PORT:-3200}"
echo ""
echo "Next steps:"
echo "  1. Add OAuth credentials to $ENV_FILE"
echo "  2. Start the service: sudo systemctl start aionima-id"
echo "  3. Configure AGI: set idService.local.enabled = true in ~/.agi/aionima.json"
